#!/bin/bash
mkdir -p img/blog

curl -s -o "img/blog/el-geoportal-municipal-en-urbigis-el-caso-de-la-comunidad-de.png" "https://info.urbigis.com/wp-content/uploads/2025/01/Captura-de-pantalla-2025-01-15-135137.png"
echo "✓ el-geoportal-municipal-en-urbigis-el-caso-de-la-co"
curl -s -o "img/blog/la-gestion-documental-en-urbigis.png" "https://info.urbigis.com/wp-content/uploads/2023/03/Captura-de-pantalla-2023-03-22-182807.png"
echo "✓ la-gestion-documental-en-urbigis"
curl -s -o "img/blog/como-crear-un-indicador-ods-con-urbigis.png" "https://info.urbigis.com/wp-content/uploads/2022/04/Captura-de-pantalla-2022-04-12-095740.png"
echo "✓ como-crear-un-indicador-ods-con-urbigis"
curl -s -o "img/blog/cuadros-de-mando-en-urbigis.png" "https://info.urbigis.com/wp-content/uploads/2021/07/Captura18.png"
echo "✓ cuadros-de-mando-en-urbigis"
curl -s -o "img/blog/compruebe-si-los-mapas-de-su-organizacion-estan-en-el-catalo.png" "https://info.urbigis.com/wp-content/uploads/2021/07/Captura17.png"
echo "✓ compruebe-si-los-mapas-de-su-organizacion-estan-en"
curl -s -o "img/blog/algunos-comentarios-sobre-los-servicios-geoespaciales-y-las-.png" "https://info.urbigis.com/wp-content/uploads/2021/07/Captura13.png"
echo "✓ algunos-comentarios-sobre-los-servicios-geoespacia"
curl -s -o "img/blog/novedades-2021-en-urbigis.png" "http://info.urbigis.com/wp-content/uploads/2021/05/Captura3.png"
echo "✓ novedades-2021-en-urbigis"
curl -s -o "img/blog/planificacion-digital-la-solucion-de-urbigis.png" "http://info.urbigis.com/wp-content/uploads/2021/02/gonzalez-due1.png"
echo "✓ planificacion-digital-la-solucion-de-urbigis"
curl -s -o "img/blog/geoportales-un-modo-diferente-de-compartir-informacion.jpg" "http://info.urbigis.com/wp-content/uploads/2020/10/arquitectura-ide-sevilla.jpg"
echo "✓ geoportales-un-modo-diferente-de-compartir-informa"
curl -s -o "img/blog/spatial-computing-y-los-nuevos-dispositivos-de-realidad-aume.jpg" "http://info.urbigis.com/wp-content/uploads/2020/09/virtual1.jpg"
echo "✓ spatial-computing-y-los-nuevos-dispositivos-de-rea"
curl -s -o "img/blog/geotransacciones-en-urbigis.png" "http://info.urbigis.com/wp-content/uploads/2020/07/geo1.png"
echo "✓ geotransacciones-en-urbigis"
curl -s -o "img/blog/covid19-en-la-era-de-los-sistemas-de-informacion-geografica.png" "http://info.urbigis.com/wp-content/uploads/2020/05/covid2-1024x661.png"
echo "✓ covid19-en-la-era-de-los-sistemas-de-informacion-g"
curl -s -o "img/blog/servicios-de-localizacion-presente-y-futuro.png" "http://info.urbigis.com/wp-content/uploads/2020/02/loc4.png"
echo "✓ servicios-de-localizacion-presente-y-futuro"
curl -s -o "img/blog/urbithings-cambia-de-nombre-a-urbigis.png" "http://info.urbigis.com/wp-content/uploads/2020/01/urbigis2-300x87.png"
echo "✓ urbithings-cambia-de-nombre-a-urbigis"
curl -s -o "img/blog/nuevos-geoportales-urbithings-de-los-cantones-de-ecuador.png" "http://info.urbigis.com/wp-content/uploads/2020/01/webs1.png"
echo "✓ nuevos-geoportales-urbithings-de-los-cantones-de-e"
curl -s -o "img/blog/publicando-un-visor-turistico-en-urbithings.png" "http://info.urbigis.com/wp-content/uploads/2019/12/chin1-min.png"
echo "✓ publicando-un-visor-turistico-en-urbithings"
curl -s -o "img/blog/crear-rapidamente-localizadores-en-urbithings.png" "http://info.urbigis.com/wp-content/uploads/2019/12/boa4.png"
echo "✓ crear-rapidamente-localizadores-en-urbithings"
curl -s -o "img/blog/nuevos-indicadores-ods-locales-como-resultado-de-la-gestion-.png" "http://info.urbigis.com/wp-content/uploads/2019/11/odsCUADRO2.png"
echo "✓ nuevos-indicadores-ods-locales-como-resultado-de-l"
curl -s -o "img/blog/una-propuesta-de-indicadores-ods-locales-el-caso-de-tulancin.png" "http://info.urbigis.com/wp-content/uploads/2019/11/tulancingo6-300x154.png"
echo "✓ una-propuesta-de-indicadores-ods-locales-el-caso-d"
curl -s -o "img/blog/publicar-planeamiento-vectorial-cad-en-urbithings.png" "https://info.urbigis.com/wp-content/uploads/2019/06/Abegondo1.png"
echo "✓ publicar-planeamiento-vectorial-cad-en-urbithings"
curl -s -o "img/blog/la-informacion-espacial-tiene-precio.png" "https://info.urbigis.com/wp-content/uploads/2017/05/collaborative_project_management_as_a_solution2.png"
echo "✓ la-informacion-espacial-tiene-precio"
curl -s -o "img/blog/embedding-a-urbithings-window-in-your-web.png" "https://info.urbigis.com/wp-content/uploads/2019/02/registro.png"
echo "✓ embedding-a-urbithings-window-in-your-web"
curl -s -o "img/blog/incrustando-una-ventana-de-urbithings-en-tu-web.png" "https://info.urbigis.com/wp-content/uploads/2019/02/registro.png"
echo "✓ incrustando-una-ventana-de-urbithings-en-tu-web"
curl -s -o "img/blog/en-este-ano-2019-hace-30-anos-que-nacio-badur.jpg" "https://info.urbigis.com/wp-content/uploads/2019/03/Estado-del-Planeamiento_3.jpg"
echo "✓ en-este-ano-2019-hace-30-anos-que-nacio-badur"
curl -s -o "img/blog/crear-una-ide-en-urbithings.png" "https://info.urbigis.com/wp-content/uploads/2019/02/registro.png"
echo "✓ crear-una-ide-en-urbithings"
curl -s -o "img/blog/mapas-de-datos-abiertos-en-urbithings.png" "https://info.urbigis.com/wp-content/uploads/2019/02/ver-mapa.png"
echo "✓ mapas-de-datos-abiertos-en-urbithings"
curl -s -o "img/blog/usando-urbithings-para-crear-un-mapa-del-paro-en-espana.png" "https://info.urbigis.com/wp-content/uploads/2019/02/Fichero.png"
echo "✓ usando-urbithings-para-crear-un-mapa-del-paro-en-e"
curl -s -o "img/blog/el-mito-del-crecimiento-sostenible.png" "https://info.urbigis.com/wp-content/uploads/2018/10/103.png"
echo "✓ el-mito-del-crecimiento-sostenible"
curl -s -o "img/blog/desarrollando-la-smart-city.png" "https://info.urbigis.com/wp-content/uploads/2018/10/99-2.png"
echo "✓ desarrollando-la-smart-city"
curl -s -o "img/blog/datos-espaciales-abiertos-nuevas-funciones-urbithings.png" "https://info.urbigis.com/wp-content/uploads/2018/03/Captura.png"
echo "✓ datos-espaciales-abiertos-nuevas-funciones-urbithi"
curl -s -o "img/blog/servicios-mapas-filon-datos-inexplorado.png" "https://info.urbigis.com/wp-content/uploads/2018/01/Captura.png"
echo "✓ servicios-mapas-filon-datos-inexplorado"
curl -s -o "img/blog/utags-una-ontologia-semantica-tecnologia-urbana.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2016/07/Ontologia.png"
echo "✓ utags-una-ontologia-semantica-tecnologia-urbana"
curl -s -o "img/blog/ulinks-un-red-de-innovacion-urbana.jpg" "https://info.urbigis.com/wp-content/uploads/2016/07/97.jpg"
echo "✓ ulinks-un-red-de-innovacion-urbana"
curl -s -o "img/blog/el-barrio-en-el-imaginario-colectivo.jpg" "https://info.urbigis.com/wp-content/uploads/2016/07/15.jpg"
echo "✓ el-barrio-en-el-imaginario-colectivo"
curl -s -o "img/blog/los-ayuntamientos-y-el-territorio-virtual-en-la-era-internet.png" "https://info.urbigis.com/wp-content/uploads/2016/07/23.png"
echo "✓ los-ayuntamientos-y-el-territorio-virtual-en-la-er"
curl -s -o "img/blog/sistematizando-los-derechos-y-obligaciones-urbanas-globales.png" "https://info.urbigis.com/wp-content/uploads/2016/06/25.png"
echo "✓ sistematizando-los-derechos-y-obligaciones-urbanas"
curl -s -o "img/blog/sistematizando-la-ejecucion-urbana-global.png" "https://info.urbigis.com/wp-content/uploads/2016/06/36.png"
echo "✓ sistematizando-la-ejecucion-urbana-global"
curl -s -o "img/blog/sistematizando-la-planificacion-urbana-global.png" "https://info.urbigis.com/wp-content/uploads/2016/06/36.png"
echo "✓ sistematizando-la-planificacion-urbana-global"
curl -s -o "img/blog/neurofisiologia-urbana.png" "https://info.urbigis.com/wp-content/uploads/2016/06/57.png"
echo "✓ neurofisiologia-urbana"
curl -s -o "img/blog/things-un-sistema-cvgi-informacion-geografica-por-colaboraci.png" "https://info.urbigis.com/wp-content/uploads/2016/03/60.png"
echo "✓ things-un-sistema-cvgi-informacion-geografica-por-"
curl -s -o "img/blog/la-tecnologia-urbana-como-arma-contra-el-cambio-climatico.png" "https://info.urbigis.com/wp-content/uploads/2015/10/62.png"
echo "✓ la-tecnologia-urbana-como-arma-contra-el-cambio-cl"
curl -s -o "img/blog/proyectos-de-automatas-urbanos-en-el-internet-de-las-cosas.jpg" "https://info.urbigis.com/wp-content/uploads/2015/09/24.jpg"
echo "✓ proyectos-de-automatas-urbanos-en-el-internet-de-l"
curl -s -o "img/blog/registro-urbano-una-propuesta-de-sistema-de-informacion-terr.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2015/05/Image1.png"
echo "✓ registro-urbano-una-propuesta-de-sistema-de-inform"
curl -s -o "img/blog/urbanismo-celular.jpg" "https://info.urbigis.com/wp-content/uploads/2015/01/1.jpg"
echo "✓ urbanismo-celular"
curl -s -o "img/blog/ideas-sobre-movilidad-urbana.png" "https://info.urbigis.com/wp-content/uploads/2014/10/76.png"
echo "✓ ideas-sobre-movilidad-urbana"
curl -s -o "img/blog/la-renta-la-velocidad-y-el-tamano-de-la-ciudad.png" "https://info.urbigis.com/wp-content/uploads/2014/04/85.png"
echo "✓ la-renta-la-velocidad-y-el-tamano-de-la-ciudad"
curl -s -o "img/blog/geoobjetos.jpg" "https://info.urbigis.com/wp-content/uploads/2013/12/86.jpg"
echo "✓ geoobjetos"
curl -s -o "img/blog/planeamiento-urbano-masivo.jpg" "https://info.urbigis.com/wp-content/uploads/2013/10/92.jpg"
echo "✓ planeamiento-urbano-masivo"
curl -s -o "img/blog/los-sistemas-de-informacion-urbanistica.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2013/09/Circuitos.png"
echo "✓ los-sistemas-de-informacion-urbanistica"
curl -s -o "img/blog/urban-components.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2012/07/Parabrisas.png"
echo "✓ urban-components"
curl -s -o "img/blog/componentes-urbanos.jpg" "https://info.urbigis.com/wp-content/uploads/2012/07/93.jpg"
echo "✓ componentes-urbanos"
curl -s -o "img/blog/la-red-viaria-puede-ser-un-espacio-controlado-terrestre.jpg" "https://info.urbigis.com/wp-content/uploads/2012/07/imagegallery-49378-58db71641a5c6.jpg"
echo "✓ la-red-viaria-puede-ser-un-espacio-controlado-terr"
curl -s -o "img/blog/planeamiento-digital.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2012/06/LinkedIn_16x16.png"
echo "✓ planeamiento-digital"
curl -s -o "img/blog/collaborative-city.png" "https://info.urbigis.com/wp-content/uploads/2012/06/89-1.png"
echo "✓ collaborative-city"
curl -s -o "img/blog/ciudad-colaborativa.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2012/06/OpenStreetMap.png"
echo "✓ ciudad-colaborativa"
curl -s -o "img/blog/location-services-an-emerging-technology.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2012/06/LinkedIn_16x16.png"
echo "✓ location-services-an-emerging-technology"
curl -s -o "img/blog/servicios-de-ubicacion-una-tecnologia-emergente.png" "http://www.arnaizpartners.com/blogarnaizpartners/wp-content/uploads/2012/06/LinkedIn_16x16.png"
echo "✓ servicios-de-ubicacion-una-tecnologia-emergente"

echo "Listo"