backend:
  name: github
  repo: ignacio-arnaiz/urbigis_web
  branch: main

media_folder: "img/blog"
public_folder: "/img/blog"

site_url: https://ignacio-arnaiz.github.io/urbigis_web

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Entrada"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    media_folder: "/img/blog"
    public_folder: "https://ignacio-arnaiz.github.io/urbigis_web/img/blog"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "tutorial"
    label: "Tutorial"
    label_singular: "Artículo"
    folder: "tutorial"
    create: true
    slug: "{{slug}}"
    extension: "md"
    media_folder: "/img/tutorial"
    public_folder: "https://ignacio-arnaiz.github.io/urbigis_web/img/tutorial"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
